# -*- coding: utf-8 -*-
"""Lec-05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTdhHmJYwR87xEHvfVJDz9VYfsYxAQB7
"""

n = int(input("Enter a number: "))
x = int(input("Enter the digit you want to find: "))
y = str(n)
count = 0

for i in range(len(y)):
    if int(y[i]) == x:
         break
    count+=1

print(f"The digit {x} appears at {count} times in {n}.")

main_password = input("Save you new password: ")

password = input("Enter correct password: ")
count = 0
for i in range (3):
  if(password == main_password):
    print("You are welcome")
    break
  else:
    password = input("Enter again: ")
  count+=1

if(count>=3):
  d
     print("You are an invalid user, get lost.")

n=5
while n>0:
  print(n)
  n=n-1
print("blastoff!")
print(n)

n = input("Enter alphanumeric character: ")
count  = 0
for char in n:
  if char.isalnum():
    count+=1
print(count)

sum = 0
while True:
  n = int(input("Enter value: "))
  if n<0:
    break
  sum = sum + n

print(sum)

n = 15
while n<=30:
  print(n)
  n=n+1

n = int(input("Enter the value of n: "))
sum = 0
while n>0:
  sum = sum+n
  n=n-1
print(sum)

shop = ['book shop','grocery shop', 'Cloth shop','Food shop']
i = 3

while i>=0:
  print(shop[i])
  i-=1
for digit in reversed(shop):
  print(digit)

n = int (input("Enter a number: "))
count= 0
org_n = n
while (n!=0):
  n=n // 10
  count+=1
print("The total digit is: ",count)
while (count > 0):
  d = org_n % 10
  print(d,end = ' ')
  org_n= org_n // 10
  count-=1

array  = [32,34,53,64,63]
len(array)
i = 0
while i < len(array)/2:
  array[i],array[len(array)-i-1] = array[len(array)-i-1], array [i]
  i+=1
print(array)

A = [3,5,7,8,12,34]
len(A)
i = 1
min = A[0]
while i<len(A):
  if(A[i]<min):
    min = A[i]
  i+=1
print(min)

A = [3,5,7,8,12,34]
len(A)
i = 1
max = A[0]
while i<len(A):
  if(A[i]>max):
    max = A[i]
  i+=1
print(max)

n =input("Enter a number: ")

while (True):
  line = input('>')
  if line == 'done':
    break
  print(line)
  print("done!")

i = 0
while i<20:
  i += 1
  if not (i% 2):
    continue
  print(i)

pass_ = '123abc'
MAX_ATTEMPT = 3
Match = False
i = 0
while i<MAX_ATTEMPT:
  password = input ("Password: ")
  i +=1
  if password == pass_:
    Match = True
    break
if Match:
  print("Access accepted")
else:
  print("Denied")

def is_palindrome_number(n):
  num = str(n)
  if num == num[::-1]:
    return True
  else:
    return False

n = input("Enter a number: ")
if is_palindrome_number(n):
  print("The number is palindrome")
else:
  print(" The number is not palindrome. ")

#grading percentage
n = int(input("Enter your number to check grade: "))
if n>100 and n<0:
  print("Invalid input")
elif n>=80 and n<=100:
  print("You got A+")
elif n>=75 and n<80:
  print("You got A")
elif n>=65 and n<70:
  print("You got A-")
elif n>=60 and n<65:
  print("You got B")
elif n>=50 and n<60:
  print("You got C")
elif n>=40 and n<50:
  print("You got D")
elif n<40:
  print("You are fail")
else:
  print("Invalid input.")

n = int(input("Enter the range: "))
for i in range (1,n+1):
  if i%2 == 0:
    print(i)

n = int(input("Enter the value to multiply: "))
for i in  range(n):
  print(f"{n}X{i} = {n*i}")

import math
n = int(input("Enter a number to check its factor: "))
for i in range (1,int(n+1)):
  if (n % i == 0):
    print(i)

n = int (input("Enter the limit: "))
a, b = 0,1
for i in range(n):
  print(a,' ',end='')
  a,b = b , a+b

import random
guess_number = random.randint(1,10)
count = 0
n = int(input("Enter a value: "))
for i in range (1,10):
  count+=1
  if guess_number == n:
    break
  else:
    n = int(input("Enter the value again: "))
if(count == 10):
  print("You failed")
else:
  print("You found at step:",count)

height = int(input("Enter the height: "))

month = int(input(" Enter the month: "))
year = int(input(" Enter year: "))

if month == 2:
  if  (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("28 days")
  else:
    print("29 days")
elif month in [4,6,9,11]:
  print("31 days")
else:
  print("30 days")

string ="bangladesh"
print(string[::1])

n = int(input("Enter the height: "))
for i in range (n ):
  print('*'*(i+1))