# -*- coding: utf-8 -*-
"""Lec 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FpO5N3bHEgnx_8B78iTxKgzk4KKCM2K
"""

for i in range (5):
  print(i)

for i in range (2,10,2):
  print(i)

fruits = ['apple','banana','dates','lemon']
for fruit in fruits:
  print(fruit)
number = [1,3,5,6]
for numbers in number:
  print(numbers)

for fruits in [1,4,6,'fa']:
  print(fruits)
for fruits in ['faruk','hasan','rakib','sazib']:
  print(fruits)

name = ['faruk','hasan','rakib','sazib']
ages = [20,34,50,55]
for name,ages in zip(name, ages):
  print(name,ages)

word = 'hello world,how are you'
for char in word:
  print(char)

word = 'hello'
for char in word:
  print(ord(char))

plaintext = 'hello'
key = 3
cipher = ''
for char in plaintext:
  cipher += chr(ord(char)+key)
print(cipher)

plaintext = 'khoor'
key = 3
cipher = ''
for char in plaintext:
  cipher += chr(ord(char)-key)
print(cipher)

student = {'Alice': 38,'Bob': 30,'Charlie': 25}
for students in student:
  print(students)
for ages in student.values():
  print(ages)

print("Items() is use to show both key and value pair")
for student,age in student.items():
  print(student, age)

name = ['Alice','Bob','Charlie']
name1 = ['Alice','Bob','Charlie']
age = [ 28,30,25]
for name , ages ,names in zip(name,age,name1):
  print(name,ages,names)

name = ['Alice','Bob','Charlie']
for index,name in enumerate(name):
  print(index,name)

for i in range(4):
  for j in range(4):
    for k in range(4):
      print('i:',i,'j:',j,'k:',k)

matrix = [[1,2,3],[4,5,6],[7,8,9]]

a = [32,34,56,67,87,98,65]
a.sort(reverse=True)
print(a[0])
print(a[1])

for i in range(1,11,1):
  print(i)

N = int(input("Enter integer number: "))
sum = 0
for i in range (1,N+1):
  sum = sum + i
print(sum)

a = 'Md Omor Faruk'
for char in a:
  print(char)

for i in range(0,21,2):
  print(i)

fact = 1
n = int(input("Enter a number: "))
for i in range(1,n+1):
  fact =fact * i
print(fact)

n = int(input("Enter the number to get its multiplication table : "))
for i in range (1,n):
  print(f"{n} * {i} = {n * i} ")

list_ = [25,65,7,8,10,34]
sum = 0
len(list_)
for i in range(len(list_)):
  if list_[i] % 2 ==0:
    sum = sum + list_[i]
print(sum)

n = int(input("Enter a number to count frequency: "))
count = 0
while(n>0):
  remainder = n % 10
  count+=1
  n = n//10
print(count)

import math
def is_prime(n):
  if(n==1):
    return False
  else:
    for i in range(2,int(math.sqrt(n)+1)):
      if n % i == 0:
        return False
    return True

start = int(input("Enter starting value:"))
end = int(input("Enter ending value:"))
for i in range (start,end + 1):
  if is_prime(i):
    print(i)

smallest = None
list_ = [25,65,7,8,10,34]
for i in list_:
  if smallest is None:
    smallest = i
  elif smallest > i :
    smallest = i
print(smallest)

digits = [0,0,0,0,0,0 ]
n = int(input("Put a number: "))
while n>0:
  d = n%10
  digits[d] +=1
  n//=10
print(digits)

list_ = [121, 223, 323, 243, 123, 232, 101]


for num in list_:

    if str(num) == list_.reverse():
        print(num)