# -*- coding: utf-8 -*-
"""Lec-08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mq3koNUl0IjWXTI-wX2siEN6E5KiqXem
"""

lst = list() #creating a list to assign
lst.append('abc') # use append to insert a value
print(lst)

lst[0] = 'xyz'  # Now we can change the value beacuse zero index exist.
print(lst)

sz = 10
lst = sz *  [0]
print(lst)
lst2 = sz * [None]
print(lst2)

language = ['python','C++','javascript','c','java','html']
print(language)
print(language[0])
language [0] = 'Python'
print(language[0])

i = 0
while i<len(language):
  print(language[i])
  i+=1

for item in language: #preferrable for using list
  print(item)

language[-1]
for each in language:
  print(each)

lnaguage = ['python','c++','javascript','c','java']  #it supports concatenation also
language2 = ['R','C#']
lan = language + language2
print(lan)

lan3 = "Python"
for each in language[::-1]:  # Slices the string in reverse
    print(each)

if 'c' in language:
  print("C exist")
else:
  print("Not exist")

dsn = 5
lists = list()
for i in range (5):
  name = input("Enter name: ")
  lists.append(name)
  i+=1
print(lists.upper)

from random import randint
lst = list()
for i in range (10):
  lst.append(randint(0,100))

print(lst)

for n in lst:
  if n%2:
    print(n)

lists = list()
n = 5
for i in range(5):
  Words = input("enter words: ")
  if(Words.startswith('b')):
    print(f"This word {Words} is start with b")
  else:
    print("Try again. ")

from random import randint
n = 10
lst = list()
for i in range (10):
  lst.append(randint(0,100))
print(lst)

for n in lst:
  if n<20 and n>10:
    print(n)

#comprehension: create a seaquence form a given sequence is called comprehension.
# for implementing searching and filtering
# newSeq = [expression for item in sequence ]
# newSeq = [expression for item in sequence if statement ]
# newSeq = [expression if statement else statement for item in sequence ]

list_ = [1,2,3,5,6,7,8]
list2 = [x for x in list_] #1
print(list2)


colors = ['yellow','black','green','blue']
fl_colores = [color for color in colors if 'e' in color] #2
print(fl_colores)


num = [2,54,6,7,7,78,1,2]
num_list = ['even' if x%2 == 0 else 'odd' for x in num]#
print(num_list)


nums = [2,10,15,5 ,54, 6, 7, 7, 78, 1, 2]
flter_list1 = [x for x in nums if x % 2 == 0 and x % 5 == 0]
print(flter_list1)


nums = [2, 54, 6, 7, 7, 78, 1, 2]
flter_list2 = [x for x in nums if x % 2 == 1 and x % 5 == 0]
print(flter_list2)

list_ = [1,24,54,67,8,9,11]
even = [x for x in list_ if x%2 == 0]
print(even)

name_list = ['faruk','omor','Arduino','Art','Basket']
start_with_e = [x for x in name_list if x.startswith('A')]
print(start_with_e)

language = [2,3,4,6,7,8]
for each in reversed(language):
  print(each)

for each2 in language[::-1]:
  print(each2)

name_list = list()
for _ in range(5):  # Collect 5 names
    name = input("Enter name: ")
    name_list.append(name)

print("Initial Name List:", name_list)

# Modify the list based on user choices
for _ in range(1):
    print("\nOptions:")
    print("1. Remove a name")
    print("2. Add a new name")
    n = input("Enter your choice (1 or 2): ")

    if n == "1":  # Remove a name
        name_to_remove = input("Enter the name to remove: ")
        if name_to_remove in name_list:
            name_list.remove(name_to_remove)
            print(f"Removed '{name_to_remove}'. Updated List: {name_list}")
        else:
            print(f"'{name_to_remove}' is not in the list.")
    elif n == "2":  # Add a new name
        name_to_add = input("Enter the name to add: ")
        name_list.append(name_to_add)
        print(f"Added '{name_to_add}'. Updated List: {name_list}")
    else:
        print("Invalid choice. Please enter 1 or 2.")

print("\nFinal Name List:", name_list)

list_numbers = list()
for i in range(5) :
  numbers = input("Enter number: ")
  list_numbers.append(numbers)
print(list_numbers)

for i in range (5):
  list_numbers[i] = int(list_numbers[i]) * int(list_numbers[i])
print(list_numbers)

list_numbers = list()
for i in range(5) :
  numbers = input("Enter number: ")
  list_numbers.append(numbers)
print(list_numbers)

squares = [x*x for x in num]
print(squares)

list_numbers = list()
for i in range(5) :
  words = input("Enter a word: ")
  if words.endswith('e'): list_numbers.append(words)

print(list_numbers)

end_e = [color for color in colors if color.endswith('e')]
print(end_e)

A_list = list()
n = True
while(n == False):
  print("1. Append.")
  print("2.Remove")
  print("3.Copy")
  print("4.Extend")
  print("5. Count")
  print("6. Sort")
  print("7.")
  while()

idx = colors.index('black')
colors[idx] = 'yellow yellow'
print(colors)

colors = ["red", "blue", "green", "yellow", "purple"]  # Example list

n = input("Enter the color name you want to delete: ")

# Check if the color exists in the list
if n in colors:
    idxs = colors.index(n)
    colors[idxs] = input("Enter the new name: ")
    print("Updated Colors List:", colors)
else:
    print("Color not found in the list.")

x = "stephen m arquard@ uct.ac.za satjan 5 09:14:16 2008"

# Split the string into words
words = x.split()

# Filter out the email address (the word containing @)
email = [word for word in words if '@' in word]

# If an email is found, print the part after '@'
if email:
    email_address = email[0].split('@')[1]
    print(email_address)  # Output: uct.ac.za

