# -*- coding: utf-8 -*-
"""Lec-03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTdhHmJYwR87xEHvfVJDz9VYfsYxAQB7
"""

n=0
while n<5:
  print(n)
  n=n+1
print("blastoff!")
print(n)

n=5
while n>0:
  print(n)
  n=n-1
print("blastoff!")
print(n)

n = 15
while n<=30:
  print(n)
  n=n+1

n = int(input("Enter the value of n: "))
sum = 0
while n>0:
  sum = sum+n
  n=n-1
print(sum)

n =1
while n<= 20:
  if n % 2 == 0:
    print(n)
  n=n+1

n =1
while n<= 20:
  if not(n % 2):
    print(n)
  n=n+1

n = int (input("Enter a number to get factorial : "))
mult =1
while n>0:
  mult = n * mult
  n=n-1
print(mult)

n = int (input("Enter a number to get multiplication table: "))
i = 1

while i <=10:
  print(n,"*",i,"=",n*i)
  i+=1

shop = ['book shop','grocery shop', 'Cloth shop','Food shop']
i = 3

while i>=0:
  print(shop[i])
  i-=1
for digit in reversed(shop):
  print(digit)

n = int (input("Enter a number: "))
count= 0
org_n = n
while (n!=0):
  n=n // 10
  count+=1
print("The total digit is: ",count)
while (count > 0):
  d = org_n % 10
  print(d,end = ' ')
  org_n= org_n // 10
  count-=1

array  = [32,34,53,64,63]
len(array)
i = 0
while i < len(array)/2:
  array[i],array[len(array)-i-1] = array[len(array)-i-1], array [i]
  i+=1
print(array)

A = [3,5,7,8,12,34]
len(A)
i = 1
min = A[0]
while i<len(A):
  if(A[i]<min):
    min = A[i]
  i+=1
print(min)

A = [3,5,7,8,12,34]
len(A)
i = 1
max = A[0]
while i<len(A):
  if(A[i]>max):
    max = A[i]
  i+=1
print(max)

n =input("Enter a number: ")

while (True):
  line = input('>')
  if line == 'done':
    break
  print(line)
  print("done!")

i = 0
while i<20:
  i += 1
  if not (i% 2):
    continue
  print(i)

pass_ = '123abc'
MAX_ATTEMPT = 3
Match = False
i = 0
while i<MAX_ATTEMPT:
  password = input ("Password: ")
  i +=1
  if password == pass_:
    Match = True
    break
if Match:
  print("Access accepted")
else:
  print("Denied")