# -*- coding: utf-8 -*-
"""Lec-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTdhHmJYwR87xEHvfVJDz9VYfsYxAQB7
"""

"""
x = 12.2
y = 124
print(x,y)
x = 100
print(x,y)
y= 300
print('x = ',x,'y =',y)
name = "Faruk"
print(name,"How are you ?")
print("Hi!",name,"How are you?")

"""


#multiple variables can assign
name,age,city = 'david',24,'German'
print(name)
print(age,city)

#One value to many variable
a=b='Hello'
print("Value a:",a,"Value: ",b)

#python just use capital letter to define as constant
print()

#Exercise
PI = 3.14
radius = 5
area = PI*radius**2
print(area)

#Swapping variables
a = 10
b = 20
print(a,b)
a , b = b , a
print (a,b)

"""
Simple Interest Calculation: Define variables P (Principal), R (Rate of
interest), and T (Time in years). Use the formula Simple Interest = (P * R * T) /
100 to calculate the interest.
"""
P = 1000
R = 0.5
T = 3
Interest = (P * R * T)/ 100
print(Interest)

"""
4. Temperature Conversion: Write a Python program that defines a variable
celsius = 37. Convert this temperature to Fahrenheit using the formula
Fahrenheit = (Celsius * 9/5) + 32.
"""
celsius = 37
Fahrenheit = (celsius * (9/5))+32
print(Fahrenheit)

"""
Rectangle Perimeter and Area: Define two variables length and width of a
rectangle. Calculate and print both the area and the perimeter of the rectangle.
"""
length = int(input("Enter the length: "))
width = float (input ("Enter the widht: "))
Area = length * width
Perimeter = 2 * (length + width)
print(Area,Perimeter)

x = 1 + 2 * 3 - 4 / 5 ** 6
print(x)

p = "faruk "
print(type(p))
print(int(3/2))
print(float(4/2))

"""
1. Write a program to prompt the user for hours and rate per hour to compute
gross pay.
"""
Hours = int(input("Enter hours: "))
Rate = float(input("Enter rate: "))
pay = Hours * Rate
print(pay)

"""
2. Record what happens when you print an assignment statement:
>>> print (n = 7)
How about this?
>>> print (7 + 5)
Or this?
>>> print (5.2, "this", 4 - 2, "that", 5/2.0)
Can you think of a general rule for what can follow the print statement? What
does the print statement return?
"""
#print (n = 7) # it returns type error
print (7 + 5)
print (5.2, "this", 4 - 2, "that", 5/2.0)

"""
3. Take the sentence: All work and no play makes Jack a dull boy. Store
each word in a separate variable, then print out the sentence on one line
using print.
"""
a = "All "
b = "work "
c ="and "
d = "no play "
e = "makes Jack a dull boy"
print(a+b+c+d+e)

"""
4. Add parenthesis to the expression 6 * 1 - 2 to change its value from 4 to
-6.
"""
a = 6 * 1 - 2
b = 6 * (1-2)
print(a, b)

"""
5. Place a comment before a line of code that previously worked, and record
what happens when you rerun the program.
"""

"""
>>> x = input()

The knights who say "ni!"
>>> x
>>> x = raw_input()
'The knights who say "ni!"'
>> x
Describe and explain each result.
"""

x = input()
#x = raw_input() gives us error
print(x)

"""
Start the Python interpreter and enter bruce + 4 at the prompt. This will
give you an error:

NameError: name 'bruce' is not defined

Assign a value to bruce so that bruce + 4 evaluates to 10.

"""
bruce = 6
print(bruce + 4)

"""
7. Write a program (Python script) named madlib.py, which asks the user to
enter a series of nouns, verbs, adjectives, adverbs, plural nouns, past tense
verbs, etc., and then generates a paragraph which is syntactically correct but
semantically ridiculous.
Once upon a time, there was a {adjective} {noun1} who loved to {verb}
{adverb}. One day, it found a group of {plural_noun} playing with a {noun2}.
The {noun1} {verb_past} with joy and decided to join them.
Together, they all {verb}ed happily ever after!
"""
noun1 = input("Enter a noun: ")
noun2 = input("Enter another noun: ")
plural_noun = input("Enter a plural noun: ")
verb_past = input("Enter a verb in past tense: ")
verb = input("Enter a verb: ")
adjective = input("Enter an adjective: ")
adverb = input("Enter an adverb: ")
print(f"Once upon a time, there was a {adjective} {noun1} who loved to {verb} {adverb}.One day, it found a group of {plural_noun} playing with a {noun2}.Together they all {verb}ed happily ever after. ")

print(bruce + 4)
print(abc+4)
